### ISSUE TITLE
[meta] Rally Core Add-On launch eng burndown list

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-core-addon#534]
**Core Add-On + RS01** – _submit an update to the Core Add-On_
- [ ] RS01 needs a badge
- [ ] RS01 final version needs to be published and ready to go on AMO
- [ ] study card information in remote settings
- [ ] consent notification implementation
- [ ] have one final QA pass with RS01 + Core Add-On
- [ ] queue up a review from add-ons team for all changes to core add-on using the data collection

**website**
- [ ] change button from "waitlist" to "install" via user agent detection
- [ ] study page details implementation
- [ ] study card (site) implementation
